name: Keep triton pod up

on:
  schedule:
    - cron: "10,30,50 * * * *"
  workflow_dispatch:

jobs:
  llm-predict-cron:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: browser-actions/setup-chrome@v1
      - run: python llm.py
        env:
          CLARIFAI_PAT_PROD: ${{ secrets.CLARIFAI_PAT_PROD }}
        
